# site settings
title: Jingkun (Allen) Liu
subtitle: Portfolio
email: nicolasgmorales@u.northwestern.edu
description: Hi! My name is Allen, welcome to my portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://allen.github.io" # the base hostname & protocol for your site
author:
street_address:
city: Chicago
state: IL
zip_code:
country: United States of America
phone: (917) 803-7037
contact_form_id: xeqdvdwn

# homepage tiles
tiles-source: projects # accepts "posts" or "pages" or "projects"
tiles-count: 10

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  LinkedIn: https://www.linkedin.com/in/jingkun-liu-709b36178/
  GitHub: https://github.com/nu-jliu
  GitLab:
  Google-Plus:
  Instagram:
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

collections:
  projects:
    output: true
    permalink: /:collection/:path/

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md
- _reference/
